const defaultCharacterSheet = {
    email: '',
    userName: '',
    characterName: '',
    raceId: '',
    raceName: '',
    classId: '',
    className: '',
    subclassId: '',
    subclassName: '',
    background: '',
    alignment: '',
    level: 1,
    xp: 0,
    baseAbilityScores: { str: 8, dex: 8, con: 8, int: 8, wis: 8, cha: 8 },
    abilityScores: { str: 8, dex: 8, con: 8, int: 8, wis: 8, cha: 8 },
    abilityMods: { str: -1, dex: -1, con: -1, int: -1, wis: -1, cha: -1 },
    proficiencyBonus: 2,
    speed: 30,
    passivePerception: 10,
    initiative: 0,
    maxHp: 1,
    currentHp: 1,
    tempHp: 0,
    hitDie: '',
    hitDiceRemaining: 1,
    armorClass: 10,
    savingThrowProficiencies: [],
    savingThrows: { str: -1, dex: -1, con: -1, int: -1, wis: -1, cha: -1 },
    skillProficiencies: [],
    expertiseProficiencies: [],
    skillValues: {},
    weaponProficiencies: [],
    armorProficiencies: [],
    toolProficiencies: [],
    languages: [],
    armorId: null,
    shieldId: null,
    equippedWeaponIds: [],
    availableWeaponIds: [],
    attacks: [],
    spellcasting: {
        classId: '',
        ability: null,
        kind: null,
        restRecovery: 'long'
    },
    spellSlots: {
        cantrips: [],
        level_1: { slotTotal: 0, slotsExpended: 0, knownSpells: [] },
        level_2: { slotTotal: 0, slotsExpended: 0, knownSpells: [] },
        level_3: { slotTotal: 0, slotsExpended: 0, knownSpells: [] },
        level_4: { slotTotal: 0, slotsExpended: 0, knownSpells: [] },
        level_5: { slotTotal: 0, slotsExpended: 0, knownSpells: [] },
        level_6: { slotTotal: 0, slotsExpended: 0, knownSpells: [] },
        level_7: { slotTotal: 0, slotsExpended: 0, knownSpells: [] },
        level_8: { slotTotal: 0, slotsExpended: 0, knownSpells: [] },
        level_9: { slotTotal: 0, slotsExpended: 0, knownSpells: [] }
    },
    spellSaveDC: null,
    spellAttackBonus: null,
    availableSpellIds: [],
    knownSpellIds: [],
    preparedSpellIds: [],
    cantripIds: [],
    resolvedSpells: { cantrips: [], known: [], prepared: [] },
    conditions: [],
    deathSaves: { successes: 0, failures: 0 },
    currency: { cp: 0, sp: 0, ep: 0, gp: 0, pp: 0 },
    traits: '',
    ideals: '',
    bonds: '',
    flaws: '',
    backstory: '',
    featureIds: [],
    features: [],
    inventory: [],
    equipment: []
};

function cloneDefaultCharacterSheet() {
    return JSON.parse(JSON.stringify(defaultCharacterSheet));
}

module.exports = {
    cloneDefaultCharacterSheet
};
